### ISSUE TITLE
magic issue on windows?

### ISSUE THREAD

**Issue by epicfaace** [kaleidos/django-validated-file#12]
It looks from the [python-magic documentation](https://github.com/ahupp/python-magic) that:

>  You will need to copy the file magic out of [binary-zip]\share\misc, and pass it's location to Magic(magic_file=...). 

I noticed that in this library, though, `magic_file` is not passed as a parameter when Magic is initialized -- [the code](https://github.com/kaleidos/django-validated-file/blob/master/validatedfile/fields.py) is merely `magic.Magic(mime=True)`. Is there another way that this library works with Windows -- or does the existing source code only work for Linux/Mac?

**Comment by hirunatan** [comment]
Issue fixed, thanks to epicfaace
